apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: cluster
  namespace: external-secrets
spec:
  provider:
    ibm:
      auth:
        secretRef:
          secretApiKeySecretRef:
            name: ibmcloud-credentials
            namespace: kube-system
            key: ibmcloud_api_key
      serviceUrl: >-
        https://1da624c1-8b9b-41f7-bed6-bc62677e365b.eu-de.secrets-manager.appdomain.cloud